version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db2
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: ulem_tracker2
    volumes:
      - postgres_data2:/var/lib/postgresql/data

volumes:
  postgres_data2:
